services:
  db:
    image: "mongo:7.0.8"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: taskManagementDb
    container_name: todo-app-db
    ports:
      - 27017:27017

  mongo-express:
    image: "mongo-express"
    restart: always
    ports:
      - 8082:8081
    container_name: todo-app-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://root:123456@db:27017/
      ME_CONFIG_BASICAUTH: false
